sudo: required
dist: trusty
language: generic
script: make
before_deploy:
- openssl aes-256-cbc -K $encrypted_d6626e7dbf67_key -iv $encrypted_d6626e7dbf67_iv -in signing.key.enc -out signing.key -d
- make deploy
deploy:
  provider: releases
  api_key:
    secure: wEKeOQEwEC/t0YESka0w1krXhKAKUgY9qTsv7ujgfYuxMbV+WEIs4pJiK7X/zxwRfH9+xUcT55yCiQ2KxPSTuP8rJRm9kpXxVPE1QXhqIAHwfMUBPVw0Ke2gubf4hWCfGAxUfI1JeTESd6kPHT6fE/jFNhH0B8Zo6fRligN2O5cxg/5bfcyDx8njkcPal0gd8rfXyXihjUctaFOE/tXc93z13uC7BPnESbZ6VKsPeHWsanClAY03LrmJOCGLwc6PNm+AJjC+XVZhrxuN3MfxzTRzqZ+or1OkMQVW1XjW0A9sRDhFNna8iLJzCanWCr4io6ObsdquHFclU3D36mU3bAna6IoThDmHpWYu6mfVBfrS90LQ4dBWfyPkG7+oKI+rUwEUXfUZfdlqAN/vLS5Jq4BnOVWTHqCb5E00MtPnWWh1aBk0Yn6lxT3EZYjwvcZarQ3P2AHtTx8EP0/a/C6H/519+WGM8fFPAjAcc0K8ASiFlhpj4UxGHnvYFTMHVUTj0PSfPB5dDMbuoRxrDxr23Mb6esbmpN/4x8nkCQaQ/f355tLLiekz9edqxXYAu1yEoHYTe3g2oW7CabWLy6mlsgjTP+cQacJHGyBMD4iEp51XgmCFnUQCArwVjAyI/AaQ+dyR2IAwE7SgC0Xt1hMgnGO4gVd9G26xaxc+qJf/XuQ=
  file:
    - dist/dit4c-imageserver-filesystem.linux.amd64.aci
    - dist/dit4c-imageserver-filesystem.linux.amd64.aci.asc
  on:
    tags: true
    repo: dit4c/dit4c-imageserver-filesystem
  skip_cleanup: true
